<?php
$data = [
    0 => [
        "Boucherie",
        "Boucherie-charcuterie",
        "Boulangerie",
        "Boutique de café",
        "Brasserie",
        "Cave à vins",
        "Caviste",
        "Crêperie",
        "Fabricant de produits alimentaires",
        "Fabricant de thé",
        "Fournisseur de bières",
        "Fournisseur de produits alimentaires",
        "Grossiste en vins et spiritueux",
        "Livraison de repas à domicile",
        "Magasin d'alcool",
        "Magasin d'alimentation bio",
        "Magasin de bonbons",
        "Magasin de cannabis",
        "Magasin de cigarettes électroniques",
        "Magasin de produits gourmets",
        "Magasin de thé",
        "Magasin de vaporiseurs",
        "Magasin de vins et spiritueux",
        "Marché aux poissons et fruits de mer",
        "Saladerie",
        "Service de traiteur",
        "Supermarché",
        "Traiteur",
        "Vignoble",
        "Épicerie fine",
        "Épicerie japonaise",
    ],
    1 => [
        "Animalerie",
        "Aquarium",
        "Centre de randonnée équestre",
        "Garde d'animaux de compagnie",
        "Magasin d'alimentation animale",
        "Magasin d'aquariophilie",
        "Magasin d'articles pour animaux",
        "Service d'adoption d'animaux de compagnie",
        "Service d'assistance",
    ],
    2 => ["Argent & assurance",
        "Administration immobilière",
        "Agence d'assurance",
        "Agence de crédit",
        "Agence de location d'appartements",
        "Agence de location immobilière",
        "Agence de recouvrement des dettes",
        "Agence de revenus",
        "Agence immobilière",
        "Agents immobiliers",
        "Assurance auto",
        "Banque",
        "Banque du secteur privé",
        "Bourse",
        "Bureau de change",
        "Cabinet d'expertise comptable",
        "Compagnie d'assurance",
        "Compagnie d'assurance voyage",
        "Conseil en déclaration fiscale",
        "Conseil en investissement",
        "Conseiller fiscal",
        "Consultant immobilier",
        "Courtier d'assurances",
        "Courtier en finances",
        "Courtier en prêts hypothécaires",
        "Entreprise de négoce de l'or et de l'argent",
        "Expert immobilier",
        "Gestion des biens",
        "Institution financière",
        "Maison de campagne",
        "Marchand d'or",
        "Mutuelle de santé",
        "Service d'allégement de la dette",
        "Service de conseil en crédit",
        "Service de crypto-monnaie",
        "Service de finances alternatives",
        "Service de remise en espèces",
        "Service de transfert d'argent",
        "Société d'investissement",
        "Société financière non banquière",
    ],
    3 => [
        "Boutique d'articles de toilette",
        "Boutique de santé et beauté",
        "Centre de bien-être",
        "Clinique de transplantation de cheveux",
        "Clinique dermatologique",
        "Coiffeur",
        "Coiffeur mobile",
        "Distributeur de produits de beauté",
        "Distributeur de produits pour la peau",
        "Entreprise de cosmétique",
        "Fournisseur d'extension de cheveux",
        "Fournisseur de produits de beauté",
        "Grossiste en produits cosmétiques",
        "Grossiste en produits de beauté",
        "Herboristerie",
        "Industrie cosmétique",
        "Institut de beauté",
        "Institut de massages",
        "Magasin d'accessoires de massage",
        "Magasin d'articles de coiffure pour hommes",
        "Magasin de cosmétiques",
        "Magasin de produits capillaires",
        "Magasin de produits de beauté",
        "Magasin de vitamines et compléments alimentaires",
        "Masseur",
        "Parfumerie",
        "Programme de bien-être",
        "Salon d'épilation",
        "Salon de manucure",
        "Salon de piercing",
        "Salon de tatouage et piercing",
        "Service de fitness et nutrition",
        "Soin des pieds",
        "Spa de jour",
        "Studio de yoga",
        "Tatoueur",
    ],
    4 => ["Architecte",
        "Chauffagiste",
        "Consultant en acoustique",
        "Designer Paysagiste",
        "Entrepreneur",
        "Entrepreneur en toiture",
        "Entrepreneur spécialisé dans l'isolation",
        "Entrepreneur spécialisé dans les systèmes de CVC",
        "Entreprise de construction",
        "Fabricant",
        "Fabricant de produits en tissu",
        "Fournisseur d'équipement",
        "Fournisseur d'équipement de nettoyage et d'entretien",
        "Fournisseur d'équipement électrique",
        "Fournisseur de filtres à eau",
        "Fournisseur de matériaux de construction",
        "Fournisseur de traitement de l'eau",
        "Fournisseurs de produits en métal",
        "Graveur",
        "Ingénieur en mécanique",
        "Magasin d'outillage",
        "Magasin d'équipements et accessoires nautiques",
        "Magasin de materiaux de construction",
        "Magasin de matériel pour piscines",
        "Magasin de matériel électrique",
        "Magasin de vêtements de sécurité",
        "Maçon",
        "Menuisier",
        "Société de construction",
        "Société de construction de piscines",
        "Vendeur de machines de construction",
    ],
    5 => ["Architecte",
        "Chauffagiste",
        "Consultant en acoustique",
        "Designer Paysagiste",
        "Entrepreneur",
        "Entrepreneur en toiture",
        "Entrepreneur spécialisé dans l'isolation",
        "Entrepreneur spécialisé dans les systèmes de CVC",
        "Entreprise de construction",
        "Fabricant",
        "Fabricant de produits en tissu",
        "Fournisseur d'équipement",
        "Fournisseur d'équipement de nettoyage et d'entretien",
        "Fournisseur d'équipement électrique",
        "Fournisseur de filtres à eau",
        "Fournisseur de matériaux de construction",
        "Fournisseur de traitement de l'eau",
        "Fournisseurs de produits en métal",
        "Graveur",
        "Ingénieur en mécanique",
        "Magasin d'outillage",
        "Magasin d'équipements et accessoires nautiques",
        "Magasin de materiaux de construction",
        "Magasin de matériel pour piscines",
        "Magasin de matériel électrique",
        "Magasin de vêtements de sécurité",
        "Maçon",
        "Menuisier",
        "Société de construction",
        "Société de construction de piscines",
        "Vendeur de machines de construction",
    ],
    6 => ["Accessoires de meubles",
        "Chaudronnerie",
        "Cheministe",
        "Cuisiniste",
        "Décorateur d'intérieur",
        "Fabricant de meubles",
        "Fourisseur de construction de jardin",
        "Fournisseur d'accessoires de meubles",
        "Fournisseur d'équipement d'irrigation du terrain",
        "Fournisseur d'équipements d'énergie solaire",
        "Fournisseur de bois de chauffage",
        "Fournisseur de chauffage",
        "Fournisseur de produits de nettoyage",
        "Fournisseur de semences",
        "Grossiste en céramiques",
        "Jardinerie",
        "Jardinier",
        "Magasin",
        "Magasin d'ameublement et de décoration",
        "Magasin d'articles de barbecue",
        "Magasin d'articles de salle de bains",
        "Magasin d'articles irlandais",
        "Magasin d'équipement de sécurité",
        "Magasin de bricolage",
        "Magasin de canapés",
        "Magasin de carrelage",
        "Magasin de couteaux",
        "Magasin de design et de décor intérieur",
        "Magasin de décorations de Noël",
        "Magasin de garnitures de portes et fenêtres",
        "Magasin de linge de maison",
        "Magasin de literie",
        "Magasin de lits",
        "Magasin de luminaires",
        "Magasin de maroquinerie",
        "Magasin de matériel de cuisine",
        "Magasin de matériel de motoculture",
        "Magasin de meubles",
        "Magasin de meubles de bureau",
        "Magasin de meubles de chambre à coucher",
        "Magasin de meubles de salon",
        "Magasin de plantes artificielles",
        "Magasin de portes",
        "Magasin de rideaux et stores",
        "Magasin de réfrigérateurs",
        "Magasin de rénovation",
        "Magasin de systèmes de climatisation",
        "Marché aux fleurs",
        "Miroiterie",
        "Pépinière",
        "Quincaillerie",
        "Rénovateur de salle de bains",
        "Service d'installation du gaz",
        "Service de décoration florale",
        "Service de location de meubles",
    ],
    7 => ["Agence de communication pour les réseaux sociaux",
        "Agence de photos",
        "Blogger",
        "Chaîne de télévision",
        "Librairie",
        "Librairie de bandes dessinées",
        "Magasin de musique",
        "Maison d'édition",
        "Photographe",
        "Producteur de film et vidéo",
        "Relieur",
        "Service d'impression de photos",
        "Service d'informations",
        "Service de montage vidéo",
        "Société de presse",
        "Société de production vidéo",
        "Station de radio",
        "Studio de création de books photographiques pour modèles",
        "Éditeur",
    ],
    8 => ["Bar",
        "Bar à cocktails",
        "Bar à tapas",
        "Restaurant",
        "Restaurant brunch",
        "Restaurant français",
        "Service de commande de repas en ligne",
        "Service à emporter",
    ],
    9 => ["Acupuncteur",
        "Cabinet dentaire",
        "Centre d'ophtalmologie",
        "Centre de soins prénatals",
        "Clinique de chirurgie plastique",
        "Conseiller familial",
        "Conseiller santé",
        "Dentiste",
        "Fournisseur d'équipement de mobilité",
        "Fournisseur d'équipement de physiothérapie",
        "Fournisseur d'équpement médical",
        "Fournisseur de lentilles de contact",
        "Grossiste en lunettes",
        "Hôpital privé",
        "Kinésithérapeute",
        "Laboratoire d'analyse médicale",
        "Magasin d'appareils auditifs",
        "Matériel et équipement d'hôpital",
        "Médecin",
        "Ostéopathe",
        "Pharmacie",
        "Pharmacie en ligne",
        "Poste de secours",
        "Praticien de médecine alternative",
        "Praticien en médecine holistique",
        "Prescription de médicaments en ligne",
        "Psychothérapeute",
        "Résidences pour personnes âgées",
        "Service d'hypnothérapie",
        "Service de référencement de médecins",
        "Service de soins à domicile",
        "Service de test de paternité",
    ],
    10 => ["Compagnie des eaux",
        "Compagnie gazière",
        "Entreprise d'énergie thermique",
        "Fournisseur d'électricité",
        "Fournisseur d'énergie",
        "Fournisseur d'énergie verte",
        "Société d'énergie solaire",
    ],
    11 => ["Agence de communication",
        "Agence de consultants commerciaux et informatiques",
        "Agence de design",
        "Agence de marketing",
        "Agence de marketing en ligne",
        "Centre d'affaires",
        "Centre d'appel",
        "Concepteur de sites web",
        "Conseiller en gestion des affaires",
        "Consultant",
        "Consultant en informatique",
        "Coursier",
        "Entreprise de livraison",
        "Entreprise de logiciels de comptabilité",
        "Entrepôt",
        "Fournisseur d'équipements Eftpos",
        "Fournisseur de CRM",
        "Fournisseur de cartouches d'encre",
        "Fournisseur de matériel de bureau",
        "Fournisseur de solution e-commerce",
        "Graphiste",
        "Grossiste en éclairage",
        "Imprimeur d'étiquettes personnalisées",
        "Laboratoire",
        "Magasin d'articles d'emballage",
        "Magasin d'articles promotionnels",
        "Magasin d'emballages",
        "Magasin d'impressions et de signalisation",
        "Magasin d'imprimantes et de scanners",
        "Magasin de fournitures de bureau",
        "Magasin de matériel de bureau",
        "Papeterie",
        "Prestataire spécialisé en études de marché",
        "Recherche et développement de produits",
        "Recruteur",
        "Service SEO",
        "Service d'agents de sécurité",
        "Service d'impression numérique",
        "Service d'organisation d'événements professionnels",
        "Service de cartographie",
        "Service de comptabilité",
        "Service de divertissement en entreprise",
        "Service de location de salles de réunion et de conférence",
        "Service de marketing Internet",
        "Service de marketing affilié",
        "Service de paiement",
        "Service de paiement par carte de crédit",
        "Service de recrutement",
        "Service de récupération de données",
        "Service de stockage en nuage (cloud storage)",
        "Service de stockage et de disques durs",
        "Service e-commerce",
        "Services aux entreprises",
        "Traducteur",
    ],
    12 => ["Administration",
        "Administration gouvernementale",
        "Administration locale",
        "Avocat",
        "Avocat spécialisé en droit du travail",
        "Bibliothèque spécialisée en droit",
        "Bureau d'immatriculation",
        "Conseil",
        "Conseiller",
        "Fournisseur de services parajuridiques",
        "Régisseur",
        "Service d'assistance au règlement des petits litiges",
        "Service de médiation",
        "Services juridiques",
    ],
    13 => ["Association de construction et de gestion de logements sociaux",
        "Centre de coaching",
        "Entreprise de pompes funèbres",
        "Généalogiste",
        "Organisme des services sociaux",
        "Services d'information",
        "Syndicat",
        "Travailleur social",
    ],
    14 => ["Agence de gardiennage de maison",
        "Centre de stockage",
        "Charpentier",
        "Déménageur",
        "Entrepreneur spécialisé dans les revêtements de sol",
        "Entreprise d'étanchéité",
        "Entreprise de nettoyage de vitres",
        "Garde-meubles en libre-service",
        "Gardien de maison",
        "Homme à tout faire",
        "Maçon",
        "Peintre",
        "Plombier",
        "Serrurier",
        "Service d'entretien de pelouse",
        "Service d'entretien à domicile",
        "Service d'extermination des nuisibles",
        "Service d'installation électrique",
        "Service de contrôle des oiseaux",
        "Service de débarras de maison",
        "Service de ménage",
        "Service de ménage à domicile",
        "Service de nettoyage et d'entretien",
        "Service de protection contre les incendies",
        "Service de réparation",
        "Service de réparation de radiateurs",
        "Services de déménagement et de stockage",
        "Services de maintenance des cheminées",
        "Électricien",
    ],
    15 => ["Agence de gardiennage de maison",
        "Centre de stockage",
        "Charpentier",
        "Déménageur",
        "Entrepreneur spécialisé dans les revêtements de sol",
        "Entreprise d'étanchéité",
        "Entreprise de nettoyage de vitres",
        "Garde-meubles en libre-service",
        "Gardien de maison",
        "Homme à tout faire",
        "Maçon",
        "Peintre",
        "Plombier",
        "Serrurier",
        "Service d'entretien de pelouse",
        "Service d'entretien à domicile",
        "Service d'extermination des nuisibles",
        "Service d'installation électrique",
        "Service de contrôle des oiseaux",
        "Service de débarras de maison",
        "Service de ménage",
        "Service de ménage à domicile",
        "Service de nettoyage et d'entretien",
        "Service de protection contre les incendies",
        "Service de réparation",
        "Service de réparation de radiateurs",
        "Services de déménagement et de stockage",
        "Services de maintenance des cheminées",
        "Électricien",
    ],
    16 => ["Sport",
        "Centre de fitness",
        "Club de boxe",
        "Club de canoë-kayak",
        "Club de golf",
        "Clud d'escalade",
        "Magasin d'accessoires pour planches à voile",
        "Magasin d'articles de course à pied",
        "Magasin d'articles de danse",
        "Magasin d'articles de football",
        "Magasin d'articles de paintball",
        "Magasin d'articles de rugby",
        "Magasin d'articles de sports",
        "Magasin d'articles de sports mécaniques",
        "Magasin de matériel de plongée",
        "Magasin de patins",
        "Magasin de skateboards",
        "Magasin de skis",
        "Magasin de sports d'hiver",
        "Magasin de surf",
        "Magasin de tennis",
        "Magasin de voile",
        "Magasins d'appareils de fitness",
        "Magasins d'articles de canoë-kayak",
        "Service de location de canoës-kayaks",
        "Sports d'aventure",
        "École de danse",
    ],
    17 => ["Agence d'excursions",
        "Agence d'excursions en bateau",
        "Agence de croisières",
        "Agence de tourisme sportif",
        "Agence de visites touristiques",
        "Agence de voyages",
        "Agrégateur de voyages",
        "Attraction touristique",
        "Camps de vacances et de divertissement",
        "Chambre d'hôtes",
        "Compagnie aérienne",
        "Cottage",
        "Fournisseur d'excursions culturelles",
        "Gîte",
        "Hébergement",
        "Hôtel",
        "Hôtel-boutique",
        "Location de vacances",
        "Logement indépendant avec services",
        "Logement meublé",
        "Organiseur de vacances au ski",
        "Service d'hébergement de vacances",
        "Site de recherche de vols",
        "Séjour chez l'habitant",
        "Voyagiste",
    ],
    18 => ["Agence d'excursions",
        "Agence d'excursions en bateau",
        "Agence de croisières",
        "Agence de tourisme sportif",
        "Agence de visites touristiques",
        "Agence de voyages",
        "Agrégateur de voyages",
        "Attraction touristique",
        "Camps de vacances et de divertissement",
        "Chambre d'hôtes",
        "Compagnie aérienne",
        "Cottage",
        "Fournisseur d'excursions culturelles",
        "Gîte",
        "Hébergement",
        "Hôtel",
        "Hôtel-boutique",
        "Location de vacances",
        "Logement indépendant avec services",
        "Logement meublé",
        "Organiseur de vacances au ski",
        "Service d'hébergement de vacances",
        "Site de recherche de vols",
        "Séjour chez l'habitant",
        "Voyagiste",
    ],
    19 => ["Boîte à bac",
        "Centre d'éducation",
        "Centre de formation",
        "Centre de formation pour adultes",
        "Centre de formation à distance",
        "Coach de vie",
        "Conseiller d'orientation",
        "Cours",
        "Cours d'anglais",
        "Fournisseur de cours de langues étrangères",
        "Institution éducative",
        "Instruction à domicile",
        "Professeur particulier",
        "Service de rédaction de CV",
        "Université",
        "École",
        "École d'anglais",
        "École d'art dramatique",
        "École d'informatique",
        "École de commerce",
        "École de comptabilité",
        "École de conduite",
        "École de langue",
        "École de management",
        "École de massage",
        "École de mathématiques",
        "École de musique",
        "École de théâtre",
        "Établissement d'enseignement supérieur",
    ],
    20 => ["Assistance et services informatiques",
        "Distributeur d'appareils électroniques",
        "Entreprise de logiciels",
        "Entreprise de télécommunications",
        "Espace Internet",
        "Fabricant de matériel informatique",
        "Fournisseur d'accès Internet",
        "Fournisseur d'équipements de télécommunications",
        "Fournisseur de DNS",
        "Fournisseur de composants électroniques",
        "Fournisseur de connexion internet",
        "Fournisseur de logiciels",
        "Fournisseur de service de courriel",
        "Laboratoire photo",
        "Location de matériel électronique",
        "Magasin Hi-Fi",
        "Magasin d'accessoires informatiques",
        "Magasin d'accessoires pour téléphones mobiles",
        "Magasin d'informatique",
        "Magasin d'écrans",
        "Magasin d'électroménager",
        "Magasin d'électronique",
        "Magasin de batteries",
        "Magasin de jumelles",
        "Magasin de matériel Hi-Fi",
        "Magasin de matériel de photographie",
        "Magasin de matériel home cinéma",
        "Magasin de pièces détachées pour appareils électroménagers",
        "Magasin de pièces et de composants électroniques détachés",
        "Magasin de téléphonie mobile",
        "Magasin de télévisions",
        "Moteur de recherche",
        "Opérateur de réseau mobile",
        "Ordinateur et accessoires",
        "Plateforme de collaboration en ligne",
        "Service VPN",
        "Service d'hébergement de sites web",
        "Service de débloquage et de recyclage de téléphones",
        "Service de location d'équipement audiovisuel",
        "Service de réparation d'ordinateurs",
        "Service de réparation de matériel électrique",
        "Service de réparation de téléphones",
        "Service informatique",
        "Service internet et téléphone",
    ],
    21 => ["Assistance et services informatiques",
        "Distributeur d'appareils électroniques",
        "Entreprise de logiciels",
        "Entreprise de télécommunications",
        "Espace Internet",
        "Fabricant de matériel informatique",
        "Fournisseur d'accès Internet",
        "Fournisseur d'équipements de télécommunications",
        "Fournisseur de DNS",
        "Fournisseur de composants électroniques",
        "Fournisseur de connexion internet",
        "Fournisseur de logiciels",
        "Fournisseur de service de courriel",
        "Laboratoire photo",
        "Location de matériel électronique",
        "Magasin Hi-Fi",
        "Magasin d'accessoires informatiques",
        "Magasin d'accessoires pour téléphones mobiles",
        "Magasin d'informatique",
        "Magasin d'écrans",
        "Magasin d'électroménager",
        "Magasin d'électronique",
        "Magasin de batteries",
        "Magasin de jumelles",
        "Magasin de matériel Hi-Fi",
        "Magasin de matériel de photographie",
        "Magasin de matériel home cinéma",
        "Magasin de pièces détachées pour appareils électroménagers",
        "Magasin de pièces et de composants électroniques détachés",
        "Magasin de téléphonie mobile",
        "Magasin de télévisions",
        "Moteur de recherche",
        "Opérateur de réseau mobile",
        "Ordinateur et accessoires",
        "Plateforme de collaboration en ligne",
        "Service VPN",
        "Service d'hébergement de sites web",
        "Service de débloquage et de recyclage de téléphones",
        "Service de location d'équipement audiovisuel",
        "Service de réparation d'ordinateurs",
        "Service de réparation de matériel électrique",
        "Service de réparation de téléphones",
        "Service informatique",
        "Service internet et téléphone",
    ],
];
